#!/usr/bin/perl -w

#
# NethServer Mail Server events configuration
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);
use File::Path;

# dovecot certificate paths
my @certificates = (qw(
                /etc/pki/dovecot/private/dovecot.pem
                /etc/pki/dovecot/certs/dovecot.pem
));

# expanded templates on SAVE event
my @saveTemplates = qw(
    /etc/postfix/main.cf
    /etc/postfix/transport
    /etc/postfix/virtual
    /etc/postfix/aliases
    /etc/postfix/internal_access
    /etc/postfix/recipient_bcc
    /etc/dovecot/dovecot.conf
    /etc/pam.d/dovecot-master
    /var/lib/nethserver/sieve-scripts/before.sieve
);

# UPDATE templates
event_templates($_,
		@saveTemplates, 
		@certificates, qw(
		/etc/postfix/master.cf
		/etc/amavisd/amavisd.conf
		/etc/dovecot/master-users
                /etc/sudoers
                /etc/hosts
                /etc/dnsmasq.conf
)) foreach (qw(nethserver-mail-server-update));


# UPDATE actions/services:
event_actions('nethserver-mail-server-update', qw(
	      initialize-default-databases 00
          nethserver-mail-server-conf 20
          nethserver-mail-default-domain-create 01
	      nethserver-mail-postmap-update 30
));

event_services('nethserver-mail-server-update', qw(
	       amavisd restart
	       dovecot restart
	       rsyslog restart
	       postfix restart
           dnsmasq restart
));

#
# nethserver-mail-server-SAVE event
#

event_templates('nethserver-mail-server-save', @saveTemplates);

event_actions('nethserver-mail-server-save',
	      'nethserver-mail-postmap-update' => '30');

event_services('nethserver-mail-server-save',
	       'dovecot' => 'reload',
	       'postfix' => 'reload');



#
# pseudonym-* events expand and reload postfix table templates
#

my @pseudonymTemplates = qw(
    /etc/postfix/virtual
    /etc/postfix/internal_access
);

foreach (qw(create modify delete)) {
    event_templates('pseudonym-' . $_, @pseudonymTemplates);
    event_actions('pseudonym-'   . $_, 
		  'nethserver-mail-postmap-update' => '30',
	);
}



#
# user-* events expand and reload postfix table templates
#

my @userTemplates = (@pseudonymTemplates, '/etc/postfix/aliases');

foreach (qw(create modify delete)) {
    event_templates('user-' . $_, @userTemplates);
    event_actions('user-'   . $_, 'nethserver-mail-postmap-update' => '30');
}

event_actions('user-create', qw(
              nethserver-mail-account-update 30
));

event_actions('user-modify',
              'nethserver-mail-account-update' => '30');

event_actions('user-delete',
	      'nethserver-mail-account-cleanup' => '30');


#
# group-* events expand and reload postfix table templates
#

my @groupTemplates = (@pseudonymTemplates, '/etc/postfix/aliases');

foreach (qw(create modify delete)) {
    event_templates('group-' . $_, @groupTemplates);
    event_actions('group-'   . $_, 
		  'nethserver-mail-postmap-update' => '30');
}

event_actions('group-create', qw(
              nethserver-mail-group-change-subscriptions 14
	      nethserver-mail-account-update 30
	      nethserver-mail-group-acl-adjust 95
));

event_actions('group-modify', qw(
              nethserver-mail-group-change-subscriptions 14
	      nethserver-mail-account-update 30
	      nethserver-mail-group-acl-adjust 95
));

event_actions('group-delete', qw(
	      nethserver-mail-group-acl-cleanup 03
	      nethserver-mail-group-delete-subscriptions 16
	      nethserver-mail-account-cleanup 30
));


#
# domain-* events: expand recipient_bcc map
#
foreach (qw(create delete modify)) {
    event_templates('domain-' . $_, qw(
		    /etc/postfix/recipient_bcc
		    /etc/postfix/virtual
                    /etc/postfix/aliases
    ));
    event_actions('domain-'   . $_, qw(
         nethserver-mail-postmap-update 30
         nethserver-mail-domain-update 40
    ));
}


#
# certificate-update event
#
event_templates('certificate-update', @certificates);

event_services('certificate-update', qw(
               dovecot restart
));


#
# migration-import event (refs #1660)
#
event_actions('migration-import', qw(
    nethserver-mail-migrate-domains      30
    nethserver-mail-server-migrate       30
    nethserver-mail-migrate-mailboxes    40
));


#
# user-create-pseudonyms event (refs #1623)
#
event_templates('user-create-pseudonyms', @pseudonymTemplates);
event_actions('user-create-pseudonyms', qw(
    nethserver-mail-postmap-update 30
));

#
# group-create-pseudonyms event (refs #1795)
#
event_templates('group-create-pseudonyms', @pseudonymTemplates);
event_actions('group-create-pseudonyms', qw(
    nethserver-mail-postmap-update 30
));


#
# FIXME use runlevel-adjust to modify admin default account
#
event_actions('runlevel-adjust', qw(
    nethserver-mail-server-init-system-users 98
));

#
# profile-modify event (refs #2675)
#
event_templates('profile-modify', qw(
     /etc/postfix/aliases
));
event_actions('profile-modify', qw(
     nethserver-mail-postmap-update 30
));


