#!/usr/bin/perl -w

#
# NethServer Mail Server events configuration
#
# Copyright (C) 2012 Nethesis srl
# See COPYING for licensing informations
#

use esmith::Build::CreateLinks qw(:all);
use File::Path;

my @templates = qw(
    /etc/postfix/main.cf
    /etc/postfix/transport
    /etc/postfix/virtual
    /etc/dovecot/dovecot.conf
);

#
# UPDATE event
#

event_templates('nethserver-mail-server-update', @templates);

event_actions('nethserver-mail-server-update',
	      'initialize-default-databases' => '00',
	      'nethserver-mail-server-conf' => '20',
	      'firewall-adjust' => '30',
	      'runlevel-adjust' => '40');

event_services('nethserver-mail-server-update',
	       'postfix' => 'restart');


#
# SAVE event
#

event_templates('nethserver-mail-server-save', @templates);

event_services('nethserver-mail-server-save',
	       'dovecot' => 'reload',
	       'postfix' => 'reload');


File::Path::make_path(['root/var/lib/vmail/private', 
		       'root/var/lib/vmail/public', 
		       'root/var/lib/vmail/shared'], 		      
		      { mode => 00700 }
    );
