#!/usr/bin/perl -w

#
# NethServer Mail Server events configuration
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);
use File::Path;

# dovecot certificate paths
my @certificates = (qw(
                /etc/pki/dovecot/private/dovecot.pem
                /etc/pki/dovecot/certs/dovecot.pem
));

# expanded templates on SAVE event
my @saveTemplates = qw(
    /etc/postfix/main.cf
    /etc/postfix/transport
    /etc/postfix/virtual
    /etc/postfix/vmailbox
    /etc/postfix/aliases
    /etc/postfix/internal_access
    /etc/postfix/recipient_bcc
    /etc/dovecot/dovecot.conf
    /etc/dovecot/sieve-scripts/before.sieve
);

# When updating nethserver-directory, dovecot LDAP user acl must be set
# again, otherwise we are locked out:
event_actions('nethserver-directory-update', qw(
	      nethserver-mail-server-ldapsetup 30
));

# UPDATE, UNINSTALL templates
event_templates($_,
		@saveTemplates, 
		@certificates, qw(
		/etc/postfix/master.cf
		/etc/dovecot/ldap.conf
		/etc/sysconfig/dovecot
                /etc/dovecot/system-users
		/etc/dovecot/master-users
                /etc/dovecot/active-directory.conf
)) foreach (qw(nethserver-mail-server-update nethserver-mail-server-uninstall));


# UPDATE actions/services:
event_actions('nethserver-mail-server-update', qw(
	      initialize-default-databases 00
              nethserver-mail-default-domain-create 01
	      nethserver-mail-pseudonym-initialize 01
	      nethserver-mail-server-conf 20
	      nethserver-mail-server-ldapsetup 21
	      nethserver-mail-postmap-update 30
	      nethserver-mail-account-update 40
	      nethserver-mail-sieve-compile 50
	      firewall-adjust 60
	      runlevel-adjust 70
	      nethserver-mail-server-init-system-users 99
));

event_services('nethserver-mail-server-update',
	       'dovecot' => 'restart',
	       'postfix' => 'restart');


# UNINSTALL actions/services:
event_actions('nethserver-mail-server-uninstall',
	      'nethserver-mail-server-uninstall' => '02',
	      'firewall-adjust' => '30',
	      'runlevel-adjust' => '40');

event_services('nethserver-mail-server-uninstall',
	       'postfix' => 'reload');




#
# nethserver-mail-server-SAVE event
#

event_templates('nethserver-mail-server-save', @saveTemplates);

event_actions('nethserver-mail-server-save',
	      'nethserver-mail-sieve-compile' => '20',
	      'nethserver-mail-postmap-update' => '30');

event_services('nethserver-mail-server-save',
	       'dovecot' => 'reload',
	       'postfix' => 'reload');


File::Path::make_path('root/var/lib/vmail/user', { mode => 00700 } );

#
# pseudonym-* events expand and reload postfix table templates
#

my @pseudonymTemplates = qw(
    /etc/postfix/virtual
    /etc/postfix/vmailbox
    /etc/postfix/internal_access
);

event_actions('pseudonym-create', 'nethserver-mail-pseudonym-initialize' => '01');

foreach (qw(create modify delete)) {
    event_templates('pseudonym-' . $_, @pseudonymTemplates);
    event_actions('pseudonym-'   . $_, 
		  'nethserver-mail-postmap-update' => '30',
		  'nethserver-mail-pseudonym-update' => '30',
	);
    event_services('pseudonym-'  . $_, 'postfix' => 'reload');
}



#
# user-* events expand and reload postfix table templates
#

my @userTemplates = (@pseudonymTemplates, '/etc/postfix/aliases');

foreach (qw(create modify delete)) {
    event_templates('user-' . $_, @userTemplates);
    event_actions('user-'   . $_, 'nethserver-mail-postmap-update' => '30');
    event_services('user-'  . $_, 'postfix' => 'reload');
}

event_actions('user-create', qw(
              nethserver-mail-account-update 30
));

event_actions('user-modify',
              'nethserver-mail-account-update' => '30');

event_actions('user-delete',
	      'nethserver-mail-default-pseudonyms-delete' => '03',
	      'nethserver-mail-account-cleanup' => '30');


#
# group-* events expand and reload postfix table templates
#

my @groupTemplates = @pseudonymTemplates;

foreach (qw(create modify delete)) {
    event_templates('group-' . $_, @groupTemplates);
    event_actions('group-'   . $_, 
		  'nethserver-mail-postmap-update' => '30');
    event_services('group-'  . $_, 'postfix' => 'reload');
}

event_actions('group-create',
	      'nethserver-mail-default-pseudonyms-create' => '03',
	      'nethserver-mail-account-update' => '30',
	      'nethserver-mail-group-acl-adjust' => '95');

event_actions('group-modify',
	      'nethserver-mail-account-update' => '30',
	      'nethserver-mail-group-acl-adjust' => '95');

event_actions('group-delete',
	      'nethserver-mail-default-pseudonyms-delete' => '03',
	      'nethserver-mail-group-acl-cleanup' => '03',
	      'nethserver-mail-account-cleanup' => '30');


#
# domain-* events: expand recipient_bcc map
#
foreach (qw(create delete modify)) {
    event_templates('domain-' . $_, 
		    '/etc/postfix/recipient_bcc', 
		    '/etc/postfix/virtual',
		    '/etc/postfix/vmailbox');
    event_actions('domain-'   . $_, 'nethserver-mail-postmap-update' => '30');
}


#
# certificate-update event
#
event_templates('certificate-update', @certificates);

event_services('certificate-update', qw(
               dovecot restart
));


#
# migration-import event (refs #1660)
#
event_actions('migration-import', qw(
    nethserver-mail-migrate-domains      30
    nethserver-mail-migrate-mailboxes    40
));


#
# user-create-pseudonyms event (refs #1623)
#
event_templates('user-create-pseudonyms', @pseudonymTemplates);
event_actions('user-create-pseudonyms', qw(
    nethserver-mail-default-pseudonyms-create 00
    nethserver-mail-postmap-update 30
));
event_services('user-create-pseudonyms', qw(
    postfix reload
));


#
# nethserver-samba-save/update: expand our templates for AD integration
#
event_templates($_, qw(
    /etc/dovecot/dovecot.conf
    /etc/dovecot/active-directory.conf
)) foreach (qw(nethserver-samba-save nethserver-samba-update));
