#!/usr/bin/perl -w
use strict;
use JSON;
use File::Glob ':bsd_glob';

sub exit_error() {
    my $json = JSON->new;
    my $json_text   = $json->encode( {result => 'ERROR'} );
    print $json_text;
    exit(1);
}

my %results;

my $maildirs = '/var/lib/nethserver/vmail';
my @list = bsd_glob($maildirs.'/*/Maildir/maildirsize');
foreach (@list) {
    my $user = (split(/\//, $_))[5];
    my $tot_size = 0;
    my $tot_msg = 0;
    open(my $fh, '<', $_) or next;
    while (my $row = <$fh>) {
        chomp $row;
        if ($row =~ /(\d+)S/) {
            $results{$user}{'max'} = int($1/1024);
        } else {
            my ($size, $msg) = split(/\s/, $row);
            $tot_size += int($size);
            $tot_msg += int($msg);
        }
    }
    close($fh);
    $results{$user}{'msg'} = $tot_msg;
    $results{$user}{'size'} = int($tot_size / 1024);
    $results{$user}{'perc'} = int($tot_size / 1024 / $results{$user}{'max'} * 100);
}

my $json = JSON->new;
my $json_text   = $json->encode( \%results );
print $json_text;
exit(0);
