#!/usr/bin/perl -w
use strict;
use JSON;

sub exit_error() {
    my $json = JSON->new;
    my $json_text   = $json->encode( {result => 'ERROR'} );
    print $json_text;
    exit(1);
}

my %results;

open(OUT,"/usr/bin/doveadm -f tab quota get -A |") || exit_error();
while ( <OUT> )
{
    # Username	Quota name	Type	Value	Limit	%
    next if /^Username/;
    my @tmp = split("\t", $_);
    if ($tmp[2] eq 'STORAGE') {
        $results{$tmp[0]}{'size'} = $tmp[3];
        $results{$tmp[0]}{'max'} = $tmp[4];
        $results{$tmp[0]}{'perc'} = $tmp[5] =~ s/\s+$//; #rtrim
    } elsif ($tmp[2] eq 'MESSAGE') {
        $results{$tmp[0]}{'msg'} = $tmp[3];
    }
}
close(OUT);

my $json = JSON->new;
my $json_text   = $json->encode( \%results );
print $json_text;
exit(0);
