#!/bin/perl
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::AccountsDB;
use esmith::ConfigDB;
use File::Glob ':bsd_glob';
use File::Basename;

my $adb = esmith::AccountsDB->open();
my $cdb = esmith::ConfigDB->open_ro();

my $domain = $cdb->get('DomainName')->prop('type');

foreach ($adb->get_all_by_prop('type' => 'pseudonym')) {
     my $account = $_->prop('Account') || next;

     # skip accounts already with domain part
     next if ($account =~ /@/);

     $_->set_prop('Account', $account."@".$domain);
}

foreach (bsd_glob('/var/lib/nethserver/vmail/*')) {
    if ( -d "$_/Maildir") {
        my $name = basename($_);

        # skip special mail dirs
        next if ($name eq 'root' || $name eq 'vmail');

        # skip mail dirs already with domain part
        next if ($name =~ /@/);

        rename($_, $_."@".$domain);
    }
}
