#!/usr/bin/perl

#
# NethServer -- nethserver-mail-pseudonym-sync
#
# Synchronize system pseudonyms with user account state
#
# Copyright (C) 2012 Nethesis srl
#

use strict;

use NethServer::MailServer;

my $event = shift;
my $account = shift;

if(NethServer::MailServer->new()->deleteAccountPseudonyms($account)) {
    exit 0;
}

exit 1;


