#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Service;
use NethServer::Directory;
use User::pwent;
use User::grent;

if( ! NethServer::Service::is_enabled('dovecot')) {
    warn "dovecot service is currently not enabled, skipping ldap ACL setup.\n";
    exit 0;
}

# Get dovecot user and group id
my $dovecotUser = getpwnam('dovecot') or die('Missing dovecot user'); 
my $dovecotGroup = getgrnam('dovecot') or die('Missing dovecot group');

#
# Adjust LDAP ACLs to allow dovecot read on any field through ldapi:// socket.
#
my $ldapAccessDirective = 'by dn.exact="gidNumber=' . $dovecotGroup->gid . 
    '+uidNumber=' . $dovecotUser->uid . ',cn=peercred,cn=external,cn=auth" read';

NethServer::Directory::addAccessDirective($ldapAccessDirective, 'userPassword');
NethServer::Directory::addAccessDirective($ldapAccessDirective, '*');

