#!/usr/bin/perl

#
# NethServer -- nethserver-mail-pseudonym-initialize
#
# Initialize existing pseudonyms records in AccountsDB
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::AccountsDB;

my $event = shift || die('Missing event argument');
my $pseudonym = shift;

my $accountsDb = esmith::AccountsDB->open();
my @records = ();

if($pseudonym) {
    @records = ($accountsDb->get($pseudonym));
} else {
    @records = $accountsDb->pseudonyms();
}

foreach my $pseudonymRecord (@records) {
    my $account = $pseudonymRecord->prop('Account');
    
    # Initialize _prevAccount prop, where is stored the Account value
    # during record update.
    if( $account && ! $pseudonymRecord->prop('_prevAccount') ) {
	$pseudonymRecord->set_prop('_prevAccount', $account);
    }
}

