#!/usr/bin/perl

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Directory;
use esmith::event;


my $event = shift;
my $errors = 0;


my $ldap = NethServer::Directory->new();

my $response = $ldap->search(
    base => 'ou=People,' . NethServer::Directory::getInternalSuffix(),
    filter => "(&(objectClass=qmailUser)(uid=admin)(accountStatus=active))",
    );

if($response->count() == 0) {
    # Update admin account user
    if( ! esmith::event::event_signal('user-modify', 'admin')) {
	warn "[ERROR] failed to modify admin user";
	$errors++;
    };
}

exit($errors == 0 ? 0 : 1);
