#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
# See COPYING for licensing informations
#

use NethServer::Service;
use esmith::ConfigDB;


NethServer::Service::manage_add('nethserver-mail-server',
				'dovecot',
				'postfix');

my $configDb = esmith::ConfigDB->open() || die("Could not open ConfigDB");

my @postmapUpdateList = split(',', $configDb->get_prop('postfix', 'PostmapUpdateList'));

foreach my $table (qw(
    /etc/postfix/virtual 
    /etc/postfix/transport
)) {
    if ( ! grep($table eq $_, @postmapUpdateList) ) {
	push @postmapUpdateList, $table;
	$configDb->set_prop('postfix', 'PostmapUpdateList', join(',', @postmapUpdateList));
    }
}





