#!/usr/bin/perl

#
# NethServer -- nethserver-mail-pseudonym-create
#
# Create default account pseudonyms
#
# Copyright (C) 2012 Nethesis srl
#

use strict;

use NethServer::MailServer;

my $event = shift;
my $account = shift;

if(NethServer::MailServer->new()->createAccountDefaultPseudonyms($account)) {
    exit 0;
}

exit 1;


