#!/usr/bin/perl

#
# nethserver-mail-group-acl-cleanup
#
# Remove any group acl set on group INBOX
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;
use NethServer::MailServer;

my $accountsDb = esmith::AccountsDB->open_ro();

my $event = shift || die("Missing event argument");
my $account = shift;

my $accountRecord = $accountsDb->get($account);

if($accountRecord->prop('type') !~ /^group(-deleted)?$/) {
    die("Account `$account` is not a group");
}

if(($accountRecord->prop('MailStatus') || '') ne 'enabled') {
    exit(0);
}

my $imap = NethServer::MailServer->connectAclManager($account . '*vmail');
	    
if( ! $imap) {
    die("Could not create connection to IMAP server");
}
        
#
# Unset group ($) ACL on the INBOX folder    
#
$imap->deleteAcl('INBOX', '$' . $account);
$imap->logout();


