#!/usr/bin/perl

#
# NethServer -- nethserver-mail-pseudonym-initialize
#
# Initialize existing pseudonyms records in AccountsDB
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;

my $event = shift || die('Missing event argument');
my $pseudonym = shift;

my $accountsDb = esmith::AccountsDB->open();
my @records = ();

if($pseudonym) {
    @records = ($accountsDb->get($pseudonym));
} else {
    @records = $accountsDb->pseudonyms();
}

foreach my $pseudonymRecord (@records) {
    my $account = $pseudonymRecord->prop('Account');
    
    # Initialize _prevAccount prop, where is stored the Account value
    # during record update.
    if( $account && ! $pseudonymRecord->prop('_prevAccount') ) {
	$pseudonymRecord->set_prop('_prevAccount', $account);
    }
}

