#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use NethServer::Service;
use NethServer::Directory;
use esmith::ConfigDB;
use User::grent;
use strict;


#
# Remove the LDAP misc schema, because it conflicts with qmail schema
#
my @schemas = glob('/etc/openldap/slapd.d/cn\=config/cn\=schema/cn=\{*\}misc.ldif');
if(@schemas) {
    NethServer::Service::stop('slapd');
    unlink @schemas;
    NethServer::Service::start('slapd');
    sleep 5;
}

#
# Connect and load the qmail schema:
#
my $ldap = NethServer::Directory::connect();
$ldap->loadLdifSchema('qmail', '/etc/openldap/schema/qmail.ldif') || die("Could not load the qmail LDIF schema for dovecot");


# Refs #1516 -- Add vmail user into amavis group, to allow bayes DB
# updates through sa-learn
{
    my $amavisGroup = getgrnam('amavis') or die('Could not find amavis group');
    
    if( ! grep { $_ eq 'vmail'} @{$amavisGroup->members()} ) {
	system('/usr/sbin/usermod', qw(-a -G amavis vmail));
	if( $? != 0) {
	    die;
	}
    }

}




